### ISSUE TITLE
Error retrieving printer list

### ISSUE THREAD

**Issue by gizmo71** [flybywiresim/simbridge#109]
In the log I see
```
[FBW-SimBridge] error   12/30/2023, 09:05:18 [PrinterService] Error retrieving printers list - { stack: [ {} ] } +1ms
```
The FlyByWire installer lists out the printers without any issue, and Simbridge _used_ to be able to see them, but something changed a few months ago and since then it just hasn't worked.

**Comment by Saschl** [comment]
Should be fixed by https://github.com/flybywiresim/simbridge/commit/dbddf3e0cd41fe624c8005518a90ca8735b6da8f. Please reopen if needed.
