### ISSUE TITLE
Updating simBridge deletes all resources files

### ISSUE THREAD

**Issue by banban60** [flybywiresim/simbridge#119]
Hey guys, I encountered an issue yesterday and wanted to inform you about. Please ask if you need some more informations

System : Windows 10
Issue : All pdfs and images that were in the resources folder disappeared after update

Steps that led to the issue :
- Put a lot of pdfs and images in matching folder of resources
- Update Simbridge through the installer from version 0.5.3 to 0.5.4 (no error screen appeared)
- Check the pdfs and images folders -> everything disappeared

**Comment by alepouna** [comment]
This sound similar to https://github.com/flybywiresim/installer/issues/469. Potentially an "issue" (that is actually a feature..) with the installer wiping the folder. 

For consideration: 
1. Have the installer ignore some folders (defined either by addon configuration or just not to delete files that do not exist in the update package)
2. Have Simbridge use a different folder (set in configuration or e.g. appdata) for routes & PDF files.

**Comment by Benjozork** [comment]
I think #2 is the preferred path forward

**Comment by tracernz** [comment]
#2, and using the documents directory. AppData is for non-user accessible data stored by the app.
