### ISSUE TITLE
0.5.5: Release candidate testing

### ISSUE THREAD

**Issue by flogross89** [flybywiresim/simbridge#123]
**Notable changes:**

- Addition of A380X terrain pattern and vertical display terrain
- Moving resources folder to user folder (won't get deleted on every update)

**Testing instructions:**
Download from https://www.swisstransfer.com/d/39f736fa-8816-406d-bc12-c5361e77bf2f , extract and start. 
- Verify if TERR ON ND works as expected on the A32NX (scanning pattern as usual, placement of terrain map accurate)
- Verify if resources folder (tray icon --> Open Resources Folder) is in a user folder (Documents\FlyByWireSim\Simbridge\resources)
- Try out other SimBridge features (remote MCDU, ...)

**Comment by nebj00la** [comment]
Quality Assurance Trainee Report

Discord Username  : nebj00la
Object of testing : #123
Aircraft          : A32NX
Tier of Testing   : 1
Date              : 03/10/2024

Testing Process: 

1. Verified functionality of TERR ON ND.
2. Verified user folder, C:\Users\%username%\Documents\FlyByWireSim\Simbridge\resources.
3. Verified remote MCDU opens and is functional on both local machine and remote iPad.

Testing Results: 
Passed

Media:

<img width="342" alt="simbridge-terr-test" src="https://github.com/user-attachments/assets/421f416c-4d1e-4332-8f86-0195517664d0">
<img width="358" alt="simbridge-user-path-test" src="https://github.com/user-attachments/assets/24def5b7-6fd2-4161-b326-2b1cc8b12230">
<img width="375" alt="simbridge-mcdu-test" src="https://github.com/user-attachments/assets/54a3cd22-cc63-41c2-8694-c09a4806b8de">
<img width="987" alt="simbridge-logging-test" src="https://github.com/user-attachments/assets/94224cde-585b-41f0-a80b-95caa13bc314">

**Comment by brewers10** [comment]
Quality Assurance Trainee Report

Discord Username  : brewers_10
Object of testing : #123
Aircraft          : A32NX
Tier of Testing   : 1
Date              : 04/10/2024

Testing Process: 
- Verify if TERR ON ND works as expected on the A32NX (scanning pattern as usual, placement of terrain map accurate): **OK**
- Verify if resources folder (tray icon --> Open Resources Folder) is in a user folder (Documents\FlyByWireSim\Simbridge\resources): **OK**
- Try out other SimBridge features (remote MCDU, ...): **OK**

Testing Results: 
Passed

**Comment by flogross89** [comment]
@nebj00la @brewers10 Thanks!

**Comment by flogross89** [comment]
Preparing release now
