### ISSUE TITLE
system tray Icon still appearing after application close

### ISSUE THREAD

**Issue by Lucky38i** [flybywiresim/simbridge#15]
If simbridge is not closed via the systray icon then the systray process is not properly killed. References to properly kill the process https://github.com/felixhao28/node-systray/issues/14

**Comment by Lucky38i** [comment]
Unfortunately even with #39 merged the icon still lingers, I'll need to speak with the dev about this

**Comment by vivekbharatha** [comment]
shutdown listener might not being triggered in the normal exit, will have look at this incident today

**Comment by Lucky38i** [comment]
So it turns out in HealthController.ts it's calling `process.exit()` which isn't sending any signals for NestJS to pick up which is most likely why the listener isn't being called. I'm attemping a solution in #43

**Comment by vivekbharatha** [comment]
Ah I see your approach in the new [PR](https://github.com/flybywiresim/simbridge/pull/43/files), that seems a best way to handle this.
Thank you for the info
