### ISSUE TITLE
Avast is reporting Simbridge as infected with FileRepMalware

### ISSUE THREAD

**Issue by Sitsko1** [flybywiresim/simbridge#32]
fbw-simbridge.exe is being put into quarantine by avast anti-virus.  Reported as infected by FileRepMalware.
![FBW-Simbridge exe_Quarentine](https://user-images.githubusercontent.com/33287463/182865249-92fc0234-6297-43ef-b105-724c592e1787.png)

**Comment by frankkopp** [comment]
This is a false alarm. 
Double check with https://www.virustotal.com/gui/home/upload or something similar.
