### ISSUE TITLE
Server IP has to be configurable

### ISSUE THREAD

**Issue by joergdd123** [flybywiresim/simbridge#34]
Workstations can have more than one IP and maybe the wireless IP of the mcdu-server (e.g. to use with tablets) is not the first in the interface list. So you have to made both the server IP and Port configurable, not only the port.
Regards Joerg

**Comment by frankkopp** [comment]
Just use the correct IP then. Type it in the browser. The log or ui "open" function is just a helper which works in most but not all cases.
Configuring it to a fixed IP would not be a solution anyway as in DHCP scenarios it might change everytime you connect to a network.

**Comment by Lucky38i** [comment]
> Workstations can have more than one IP and maybe the wireless IP of the mcdu-server (e.g. to use with tablets) is not the first in the interface list. So you have to made both the server IP and Port configurable, not only the port. Regards Joerg

You can't make the IP address configurable, this is assigned by your DHCP, you can make it static through your router though. if you have your workstations with multiple interfaces with different addresses (for e.g VLANs), but they're on the same subnet then you should be able to use any of them. You also can just connect via the hostname. I'll put in a PR to display the hostname but it won't include the FQDN

**Comment by Lucky38i** [comment]
As this issue has not been replied to in close to a fortnight I'll be closing it.
