### ISSUE TITLE
thermal printer for Simbridge

### ISSUE THREAD

**Issue by robertoryan** [flybywiresim/simbridge#48]
I installed a thermal printer, it comes with a 48mm roll, but in the simbridge I already put several sizes and the letters are still very large.

**Comment by RPDengel** [comment]
The same here, with a 80mm Thermo POS Printer.
Is it possible to adjust the paper size, or use the paper-format "Roll Paper 80 x 297 mm" ?
Thank you in advance!

**Comment by frankkopp** [comment]
https://docs.flybywiresim.com/simbridge/install-configure/configuration/#printer-settings

**Comment by RPDengel** [comment]
Hi @frankkopp, thanks. The support page was not very helpful. I learned that i have to restart simbridge after do changes.

@robertoryan: my thermoprinter with 80mm paper roll is now working. Have a look at the config at the screenshotzs atached:
![Screenshot 2023-03-02 193439](https://user-images.githubusercontent.com/27812607/222520558-682748ae-3698-44ff-ae4c-69dd379cdb83.jpg)
![Screenshot 2023-03-02 193138](https://user-images.githubusercontent.com/27812607/222520593-dc428b08-dd32-490e-b941-dd5584f5a891.jpg)
![IMG_6289](https://user-images.githubusercontent.com/27812607/222520617-7d239672-28b9-4447-a7e0-6532065217e5.jpeg)

**Comment by Lucky38i** [comment]
Resolved
