### ISSUE TITLE
Support minimizing Windows Terminal to tray

### ISSUE THREAD

**Issue by Nufflee** [flybywiresim/simbridge#56]
According to [our docs](https://docs.flybywiresim.com/simbridge/troubleshooting/#main-window), the package we use for hiding the console window (`node-hide-console-window`) does not support hiding Windows Terminal. I can reproduce the same on Windows 10 using Windows Terminal.

Opening an issue to keep track of this and because it's something I'd like to look into in the future.

**Comment by Nufflee** [comment]
It turns out that Windows Terminal doesn't support being hidden completely (only minimized) because it supports multiple tabs in one window, according to [this issue](https://github.com/microsoft/terminal/issues/13248) (nothing has really been fixed in the linked PR as far as I can tell).

I believe the best course of action would be to force Simbridge to always start in `conhost` through the installer, similar to what's described [here](https://github.com/nzbget/nzbget/issues/792#issuecomment-1093350550).

**Comment by drepamig** [comment]
I edited the shortcut in `shell:startup` and that does indeed allow Simbridge to be hidden to tray.

For reference for others, I simply prepended the path in the `fbw-simbridge` shortcut with `conhost`

**Comment by Nufflee** [comment]
@drepamig thanks for testing this out! I am looking into integrating this into the installer so that it always runs in conhost, without you having to take any action so I'm glad to know that it works.

**Comment by FoxtrotSierra6829** [comment]
Fixed by #95
