### ISSUE TITLE
SimBridge doesn't stop

### ISSUE THREAD

**Issue by 2hwk** [flybywiresim/simbridge#62]
### Describe the bug

Sometimes Simbridge still runs, with a big load on the processor, after pushing the stop button.

### Expected behavior

Simbridge must stop every time the stop button is pushed.

### Steps to reproduce

1. Activate Simbridge
2. Stop Simbridge

### References (optional)

![SimBridge](https://user-images.githubusercontent.com/75140388/209956562-d487ced1-9850-4ff4-a705-de3aa10af010.jpg)

**Comment by auroraisluna** [comment]
can replicate, if simbridge is running (via npm run start) for example, connect to the airplane (via efb) and ctrl + c (kill) it still uses resources, and the console also somehow keeps outputting health messages

**Comment by jcc1953** [comment]
No more problem with release V0.4.0
