### ISSUE TITLE
Simbridge keeps restarting

### ISSUE THREAD

**Issue by deiks** [flybywiresim/simbridge#71]
Hi,

Having an issue with simbridge (latest version). Tried to remove and do clean install via installer.

Can't say much about it because there's no specific reason and timing why and when it happens. My tablet starts flashing on/off mcdu, and ND display hides terrain. What I can see in my task manager is that FlyByWire Simbridge process is restarting.

Where to continue with investigating?

**Comment by deiks** [comment]
[https://drive.google.com/file/d/17xK7SUiZbhU95BKzYHrbg7Pw7QF2S7xz/view?usp=share_link](url)

**Comment by deiks** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/4221827/224438538-4d24e36c-c804-41b0-9793-074541b24173.png)

**Comment by Lucky38i** [comment]
@deiks are you still experiencing this issue?
