### ISSUE TITLE
Extremely High Vram useage

### ISSUE THREAD

**Issue by bobstar3233** [flybywiresim/simbridge#78]
Just Simbridge its self use's anywhere from 1.6-3GB of VRAM which is not good when most GPUs have 4-8Gig VRAM and MSFS uses 4-8 depending on settings. Is there a setting to turn off hardware rendering and switch to software rendering?

**Comment by frankkopp** [comment]
This is most likely the Terrain rendering which uses the GPU. It can't be turned off. If it would be Terrain on MD would not work. Using GPU was necessary for performance.

**Comment by Lucky38i** [comment]
Is this still apparent with the latest release?

**Comment by Lucky38i** [comment]
Closing this as stale
